logging:
    level:
        ROOT: INFO
        com.slalom: INFO
        io.github.jhipster: INFO

eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://admin:admin@registry.blockchain.local:8761/eureka/

spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    cloud:
        stream:
            kafka:
                binder:
                    brokers: kafka-queue.blockchain.local
                    zk-nodes: zookeeper.blockchain.local
            bindings:
                output:
                    destination: topic-jhipster

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    security:
        authentication:
            jwt:
                secret: slalom-blockchain-hackathon-september-production-jwt-token-that-needs-to-be-very-long
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000

